### PR TITLE
New versions

### PR DESCRIPTION
**Pull request by ireun**
Hello!

I've fixed this page to include new updates. It's available at [https://ireun.github.io/aixun-changelog/](https://ireun.github.io/aixun-changelog/).

Kind regards.

### CODE REVIEW

**Comment by kolinger** [comment]
Should be fixed now https://aixun-updates.github.io/

**Comment by dd010101** [comment]
Fixed https://aixun-updates.github.io/

**Comment by dd010101** [comment]
I also fixed your broken firmware download links (for example P3208 + others) and also fixed http:// link issue where modern browsers block http:// download links. Other improvements are much better speed and reliability.

If you have any other ideas how to improve this project please let me know. Thank you for feedback.

**Comment by ireun** [comment]
I see, I knew that the download links were broken due to secure context, but I had no way of hosting these files elsewhere.

No problem, take care! :)

**Comment by ireun** [comment]
Oh one thing - there are parts in your changelog list that are not in order, and some that are duplicated ;)

**Comment by dd010101** [comment]
I see. Order should be fixed (sort is by date desceeding). Duplicated versions are removed (unique identifier is date + version string). Also date format was inconsistent (sometimes date didn't have leading zeros) - fixed that too, now leading zeros are everywhere. Also pushed AIXUN application to last tab and renamed to be less confusing.

I did also update navigation to cope better with many models. Originally there were just few but now there are so many of them... Also updated to prefer Txyz models as first followed by rest sorted by natural order.

**Comment by ireun** [comment]
Nice! BTW why you do not keep the commit history? 😅

**Comment by dd010101** [comment]
Yeah, I use github pages in weird way only as hosting. I hate to use commits as deploy tool since I make sometimes many deployments for testing purposes before functionality is done and thus making commits like "test1" "test2" or "fixing this" "fixing it again" "finally fixing it maybe" is bothersome. This is why I use script to avoid this but as side effect history is not kept.

I could create another repository to track history with meaningful messages I guess but I didn't bother with that since this was created as low effort project just to make it quickly work.

**Comment by dd010101** [comment]
I created mentioned repository for development where I will track changes via commits into the future: https://github.com/aixun-updates/aixun-updates-src. This repository also contains server-side script. If you want to see commits or contribute to development please do there.

**Pull request closed without merging**
